version: '3.6'

services:
  terraform:
    image: hashicorp/terraform:1.0.1
    container_name: terraform
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    env_file:
      - .env
    entrypoint: ash
    tty: true